-- 能碳会计 AI 智能体：当前 RAG 业务表快照
CREATE TABLE user_account (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    auth_version INT NOT NULL DEFAULT 1,
    created_by_user_id BIGINT UNSIGNED NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_account_username (username),
    KEY idx_user_account_role_status (role, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE llm_config (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope VARCHAR(16) NOT NULL DEFAULT 'USER',
    owner_user_id BIGINT UNSIGNED NOT NULL,
    provider_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
    provider_type VARCHAR(32) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NULL,
    capability VARCHAR(32) NOT NULL,
    protocol VARCHAR(32) NOT NULL,
    api_base_url VARCHAR(512) NOT NULL,
    api_key VARCHAR(512) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    supports_tool_calling TINYINT(1) NOT NULL DEFAULT 0,
    snapshot_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_llm_config_owner_model
        (scope, owner_user_id, provider_type, model_name, capability),
    KEY idx_llm_config_owner_capability (owner_user_id, capability, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE structured_asset (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    dataset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    asset_code VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    current_version_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_structured_asset_dataset_code (user_id, dataset_id, asset_code),
    KEY idx_structured_asset_dataset (user_id, dataset_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE structured_asset_version (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    asset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    dataset_id BIGINT UNSIGNED NOT NULL,
    version_label VARCHAR(64) NOT NULL,
    edition_year INT NULL,
    template_code VARCHAR(64) NOT NULL,
    state VARCHAR(24) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    raw_bucket VARCHAR(64) NOT NULL,
    raw_object_key VARCHAR(512) NOT NULL,
    profile JSON NULL,
    row_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_structured_version_hash (asset_id, content_hash),
    KEY idx_structured_version_asset_state (asset_id, state, created_at),
    KEY idx_structured_version_edition (asset_id, edition_year, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE structured_asset_alias (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    version_id BIGINT UNSIGNED NOT NULL,
    filename VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_structured_alias_filename (version_id, filename)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE structured_table (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    version_id BIGINT UNSIGNED NOT NULL,
    table_code VARCHAR(64) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    source_sheet VARCHAR(255) NOT NULL,
    source_range VARCHAR(64) NULL,
    object_bucket VARCHAR(64) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    row_count INT NOT NULL,
    schema_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_structured_table_code (version_id, table_code),
    KEY idx_structured_table_version (version_id, table_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE structured_term_alias (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    dataset_id BIGINT UNSIGNED NOT NULL,
    term VARCHAR(255) NOT NULL,
    canonical_value VARCHAR(255) NOT NULL,
    field_name VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_structured_term_alias (user_id, dataset_id, term, canonical_value),
    KEY idx_structured_term_lookup (user_id, dataset_id, term)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE structured_query_audit (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    dataset_ids JSON NOT NULL,
    request_payload JSON NOT NULL,
    status VARCHAR(16) NOT NULL,
    result_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    elapsed_ms INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_structured_query_user_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dataset (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    dense_embedding_config_id BIGINT UNSIGNED NOT NULL,
    sparse_embedding_config_id BIGINT UNSIGNED NOT NULL,
    chat_config_id BIGINT UNSIGNED NULL,
    vision_config_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_dataset_user_name (user_id, name),
    KEY idx_dataset_user_updated (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document_folder (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    dataset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    name VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_folder_user_dataset_name (user_id, dataset_id, name),
    KEY idx_document_folder_dataset (user_id, dataset_id, created_at),
    KEY idx_document_folder_parent (dataset_id, parent_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    dataset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    folder_id BIGINT UNSIGNED NULL,
    filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(32) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    content_type VARCHAR(128) NULL,
    raw_bucket VARCHAR(64) NOT NULL,
    raw_object_key VARCHAR(512) NOT NULL,
    parsed_bucket VARCHAR(64) NULL,
    parsed_object_key VARCHAR(512) NULL,
    parser_backend VARCHAR(32) NOT NULL DEFAULT 'opendataloader',
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    version INT NOT NULL DEFAULT 1,
    attempt_count INT NOT NULL DEFAULT 0,
    available_at DATETIME NULL,
    lease_token VARCHAR(64) NULL,
    lease_owner VARCHAR(128) NULL,
    lease_expires_at DATETIME NULL,
    queued_at DATETIME NULL,
    processing_started_at DATETIME NULL,
    finished_at DATETIME NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    reparse_requested TINYINT(1) NOT NULL DEFAULT 0,
    dispatch_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    dispatch_attempt_count INT NOT NULL DEFAULT 0,
    dispatch_available_at DATETIME NULL,
    dispatch_lease_token VARCHAR(64) NULL,
    dispatch_lease_expires_at DATETIME NULL,
    dispatch_error VARCHAR(1000) NULL,
    page_count INT NULL,
    chunk_count INT NOT NULL DEFAULT 0,
    parse_time_ms INT NULL,
    parse_quality_status VARCHAR(32) NULL,
    parse_quality JSON NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL_UPLOAD',
    source_url VARCHAR(1024) NULL,
    source_title VARCHAR(512) NULL,
    source_metadata JSON NULL,
    review_status VARCHAR(16) NOT NULL DEFAULT 'NOT_REQUIRED',
    review_note VARCHAR(1000) NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_user_dataset_filename (user_id, dataset_id, filename),
    KEY idx_document_dataset_created (dataset_id, created_at),
    KEY idx_document_user_status (user_id, status),
    KEY idx_document_queue_available (status, available_at, id),
    KEY idx_document_lease_expiry (status, lease_expires_at, id),
    KEY idx_document_dispatch_available (dispatch_status, dispatch_available_at, id),
    KEY idx_document_review_status (user_id, review_status, created_at),
    KEY idx_document_folder (folder_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document_chunk (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    chunk_id VARCHAR(128) NOT NULL,
    document_id BIGINT UNSIGNED NOT NULL,
    document_version INT NOT NULL DEFAULT 1,
    dataset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    chunk_type VARCHAR(32) NOT NULL DEFAULT 'text',
    start_line INT NULL,
    end_line INT NULL,
    start_page INT NULL,
    end_page INT NULL,
    structure_metadata JSON NULL,
    chunk_index INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_chunk_chunk_id (chunk_id),
    KEY idx_document_chunk_user_dataset (user_id, dataset_id),
    KEY idx_document_chunk_document_index (document_id, chunk_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE report_run (
    id VARCHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    dataset_id BIGINT UNSIGNED NOT NULL,
    document_id BIGINT UNSIGNED NOT NULL,
    document_version INT NOT NULL,
    parsed_bucket VARCHAR(64) NOT NULL,
    parsed_object_key VARCHAR(512) NOT NULL,
    report_type VARCHAR(2) NOT NULL,
    template_id VARCHAR(64) NOT NULL,
    template_version VARCHAR(32) NOT NULL,
    template_snapshot JSON NOT NULL,
    model_snapshot JSON NOT NULL,
    document_manifest JSON NOT NULL,
    custom_template_document_id BIGINT UNSIGNED NULL,
    custom_template_document_version INT NULL,
    custom_template_manifest JSON NULL,
    mode VARCHAR(16) NOT NULL DEFAULT 'GENERATE',
    language VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
    reporting_year INT NULL,
    user_instructions TEXT NULL,
    output_formats JSON NOT NULL,
    llm_config_id BIGINT UNSIGNED NOT NULL,
    llm_snapshot_version BIGINT UNSIGNED NOT NULL,
    state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    stage VARCHAR(32) NOT NULL DEFAULT 'WAITING',
    input_hash VARCHAR(64) NOT NULL,
    available_at DATETIME NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    lease_token VARCHAR(64) NULL,
    lease_owner VARCHAR(128) NULL,
    lease_expires_at DATETIME NULL,
    report_ir JSON NULL,
    checkpoint JSON NULL,
    analysis_coverage JSON NULL,
    validation_report JSON NULL,
    manifest JSON NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    dispatch_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    dispatch_attempt_count INT NOT NULL DEFAULT 0,
    dispatch_available_at DATETIME NULL,
    dispatch_lease_token VARCHAR(64) NULL,
    dispatch_lease_expires_at DATETIME NULL,
    dispatch_error VARCHAR(1000) NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_report_run_user_created (user_id, created_at),
    KEY idx_report_run_document_created (document_id, created_at),
    KEY idx_report_run_state_available (state, available_at, created_at),
    KEY idx_report_run_dispatch_available (dispatch_status, dispatch_available_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE report_question (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(36) NOT NULL,
    field_id VARCHAR(128) NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    question VARCHAR(1000) NOT NULL,
    options JSON NULL,
    required TINYINT(1) NOT NULL DEFAULT 1,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    answer JSON NULL,
    answered_by BIGINT UNSIGNED NULL,
    answered_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_report_question_field (run_id, field_id, question_type),
    KEY idx_report_question_run_status (run_id, status, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_conversation (
    id VARCHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(160) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_agent_conversation_user_updated (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_conversation_turn (
    id VARCHAR(36) NOT NULL,
    conversation_id VARCHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    turn_index INT NOT NULL,
    user_content TEXT NOT NULL,
    assistant_content LONGTEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'STREAMING',
    dataset_ids JSON NOT NULL,
    document_ids JSON NOT NULL,
    llm_config_id BIGINT UNSIGNED NULL,
    attachments JSON NOT NULL,
    interaction JSON NULL,
    report_run_id VARCHAR(36) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_turn_index (conversation_id, turn_index),
    KEY idx_agent_turn_conversation (conversation_id, turn_index),
    KEY idx_agent_turn_user_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE report_artifact (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(36) NOT NULL,
    artifact_type VARCHAR(32) NOT NULL,
    bucket VARCHAR(64) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    renderer_version VARCHAR(32) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_report_artifact_type (run_id, artifact_type),
    KEY idx_report_artifact_run (run_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
