-- 能碳会计 AI 智能体：最小 RAG 基线（四张业务表）
CREATE TABLE llm_config (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scope VARCHAR(16) NOT NULL DEFAULT 'USER',
    owner_user_id BIGINT UNSIGNED NOT NULL,
    provider_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
    provider_type VARCHAR(32) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NULL,
    capability VARCHAR(32) NOT NULL,
    protocol VARCHAR(32) NOT NULL,
    api_base_url VARCHAR(512) NOT NULL,
    api_key VARCHAR(512) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    snapshot_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_llm_config_owner_model
        (scope, owner_user_id, provider_type, model_name, capability),
    KEY idx_llm_config_owner_capability (owner_user_id, capability, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dataset (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    dense_embedding_config_id BIGINT UNSIGNED NOT NULL,
    sparse_embedding_config_id BIGINT UNSIGNED NOT NULL,
    chat_config_id BIGINT UNSIGNED NULL,
    vision_config_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_dataset_user_name (user_id, name),
    KEY idx_dataset_user_updated (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    dataset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(32) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    content_type VARCHAR(128) NULL,
    raw_bucket VARCHAR(64) NOT NULL,
    raw_object_key VARCHAR(512) NOT NULL,
    parsed_bucket VARCHAR(64) NULL,
    parsed_object_key VARCHAR(512) NULL,
    parser_backend VARCHAR(32) NOT NULL DEFAULT 'opendataloader',
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    version INT NOT NULL DEFAULT 1,
    attempt_count INT NOT NULL DEFAULT 0,
    available_at DATETIME NULL,
    lease_token VARCHAR(64) NULL,
    lease_owner VARCHAR(128) NULL,
    lease_expires_at DATETIME NULL,
    queued_at DATETIME NULL,
    processing_started_at DATETIME NULL,
    finished_at DATETIME NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    reparse_requested TINYINT(1) NOT NULL DEFAULT 0,
    dispatch_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    dispatch_attempt_count INT NOT NULL DEFAULT 0,
    dispatch_available_at DATETIME NULL,
    dispatch_lease_token VARCHAR(64) NULL,
    dispatch_lease_expires_at DATETIME NULL,
    dispatch_error VARCHAR(1000) NULL,
    page_count INT NULL,
    chunk_count INT NOT NULL DEFAULT 0,
    parse_time_ms INT NULL,
    parse_quality_status VARCHAR(32) NULL,
    parse_quality JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_document_dataset_created (dataset_id, created_at),
    KEY idx_document_user_status (user_id, status),
    KEY idx_document_queue_available (status, available_at, id),
    KEY idx_document_lease_expiry (status, lease_expires_at, id),
    KEY idx_document_dispatch_available (dispatch_status, dispatch_available_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE document_chunk (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    chunk_id VARCHAR(128) NOT NULL,
    document_id BIGINT UNSIGNED NOT NULL,
    document_version INT NOT NULL DEFAULT 1,
    dataset_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    chunk_type VARCHAR(32) NOT NULL DEFAULT 'text',
    start_line INT NULL,
    end_line INT NULL,
    start_page INT NULL,
    end_page INT NULL,
    structure_metadata JSON NULL,
    chunk_index INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_chunk_chunk_id (chunk_id),
    KEY idx_document_chunk_user_dataset (user_id, dataset_id),
    KEY idx_document_chunk_document_index (document_id, chunk_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
