// 仅用于前端本地预览。所有 ID、文件名和内容均为演示数据，不含 API Key 或真实业务数据。
export const PREVIEW_DATA_NOTICE = "本地预览数据 · 非真实服务结果";

export const mockDashboardSummary = {
  preview: true,
  datasetCount: 3,
  documentCount: 18,
  readyDocumentCount: 15,
  processingDocumentCount: 2,
  failedDocumentCount: 1,
  chunkCount: 1268,
};

export const mockModelConfigs = [
  {
    preview: true,
    id: 1001,
    scope: "USER",
    owner_user_id: 1,
    provider_id: 1,
    provider_type: "deepseek",
    model_name: "deepseek-chat-preview",
    display_name: "对话模型（预览）",
    capability: "CHAT",
    protocol: "openai",
    api_base_url: "https://example.invalid/chat",
    api_key_masked: "已配置（预览）",
    is_active: true,
    snapshot_version: 1,
    created_at: "2026-08-06T09:30:00",
    updated_at: "2026-08-08T14:20:00",
  },
  {
    preview: true,
    id: 1002,
    scope: "USER",
    owner_user_id: 1,
    provider_id: 1,
    provider_type: "qwen",
    model_name: "text-embedding-preview",
    display_name: "稠密向量（预览）",
    capability: "EMBEDDING",
    protocol: "openai",
    api_base_url: "https://example.invalid/embeddings",
    api_key_masked: "已配置（预览）",
    is_active: true,
    snapshot_version: 1,
    created_at: "2026-08-06T09:35:00",
    updated_at: "2026-08-08T14:22:00",
  },
  {
    preview: true,
    id: 1003,
    scope: "USER",
    owner_user_id: 1,
    provider_id: 1,
    provider_type: "doubao",
    model_name: "sparse-embedding-preview",
    display_name: "稀疏向量（预览）",
    capability: "SPARSE_EMBEDDING",
    protocol: "doubao_vision",
    api_base_url: "https://example.invalid/sparse",
    api_key_masked: "已配置（预览）",
    is_active: true,
    snapshot_version: 1,
    created_at: "2026-08-06T09:40:00",
    updated_at: "2026-08-08T14:24:00",
  },
  {
    preview: true,
    id: 1004,
    scope: "USER",
    owner_user_id: 1,
    provider_id: 1,
    provider_type: "qwen",
    model_name: "rerank-preview",
    display_name: "重排模型（待接入）",
    capability: "RERANK",
    protocol: "dashscope",
    api_base_url: "https://example.invalid/rerank",
    api_key_masked: "已配置（预览）",
    is_active: false,
    snapshot_version: 1,
    created_at: "2026-08-07T11:00:00",
    updated_at: "2026-08-07T11:00:00",
  },
  {
    preview: true,
    id: 1005,
    scope: "USER",
    owner_user_id: 1,
    provider_id: 1,
    provider_type: "qwen",
    model_name: "vision-preview",
    display_name: "PDF OCR / 视觉模型（预览）",
    capability: "VISION",
    protocol: "openai",
    api_base_url: "https://example.invalid/vision",
    api_key_masked: "已配置（预览）",
    is_active: true,
    snapshot_version: 1,
    created_at: "2026-08-07T11:10:00",
    updated_at: "2026-08-07T11:10:00",
  },
];

export const mockDatasets = [
  {
    preview: true,
    id: 2001,
    name: "企业碳排放核算库",
    description: "排放因子、核算边界与企业盘查指南。",
    status: "ACTIVE",
    dense_embedding_config_id: 1002,
    sparse_embedding_config_id: 1003,
    chat_config_id: 1001,
    vision_config_id: 1005,
    created_at: "2026-08-05T10:00:00",
    updated_at: "2026-08-09T16:30:00",
  },
  {
    preview: true,
    id: 2002,
    name: "节能政策与标准",
    description: "政策文件、国家标准与行业指南。",
    status: "ACTIVE",
    dense_embedding_config_id: 1002,
    sparse_embedding_config_id: 1003,
    chat_config_id: 1001,
    vision_config_id: null,
    created_at: "2026-08-06T13:20:00",
    updated_at: "2026-08-09T15:10:00",
  },
  {
    preview: true,
    id: 2003,
    name: "产品碳足迹方法库",
    description: "产品生命周期边界、数据质量与报告样例。",
    status: "ACTIVE",
    dense_embedding_config_id: 1002,
    sparse_embedding_config_id: 1003,
    chat_config_id: null,
    vision_config_id: null,
    created_at: "2026-08-07T08:45:00",
    updated_at: "2026-08-08T18:00:00",
  },
];

const baseDocument = {
  preview: true,
  parser_backend: "opendataloader",
  version: 1,
  attempt_count: 1,
};

export const mockDocumentsByDataset = {
  2001: [
    {
      ...baseDocument,
      document_id: 3001,
      dataset_id: 2001,
      filename: "温室气体排放核算指南（预览）.pdf",
      file_type: "pdf",
      file_size: 4832180,
      status: "READY",
      error_message: null,
      page_count: 42,
      chunk_count: 6,
      parse_time_ms: 18420,
      parse_quality_status: "PASSED",
      parse_quality: {
        schema_version: 2,
        status: "PASSED",
        pdf_page_count: 42,
        markdown_page_count: 42,
        text_coverage_ratio: 0.976,
        ocr_page_count: 2,
        ocr_required_pages: [],
        low_confidence_pages: [],
        warnings: [],
        fallback: {
          processed_page_count: 2,
          results: [
            { page_number: 12, method: "OCR" },
            { page_number: 31, method: "VISION" },
          ],
          warnings: [],
        },
        validation: {
          structural_passed: true,
          page_set_complete: true,
          evaluated_page_count: 42,
          blocking_issue_count: 0,
          warning_count: 0,
        },
      },
      created_at: "2026-08-09T09:10:00",
      updated_at: "2026-08-09T09:10:19",
    },
    {
      ...baseDocument,
      document_id: 3002,
      dataset_id: 2001,
      filename: "天然气排放因子表（预览）.docx",
      file_type: "docx",
      file_size: 684300,
      parser_backend: "builtin",
      status: "PROCESSING",
      error_message: null,
      page_count: null,
      chunk_count: 0,
      parse_time_ms: null,
      created_at: "2026-08-09T16:30:00",
      updated_at: "2026-08-09T16:30:00",
      processing_started_at: "2026-08-09T16:30:02",
      attempt_count: 1,
    },
    {
      ...baseDocument,
      document_id: 3003,
      dataset_id: 2001,
      filename: "扫描件示例（预览）.pdf",
      file_type: "pdf",
      file_size: 9251300,
      status: "FAILED",
      error_message: "预览失败信息：未提取到可索引文本",
      page_count: null,
      chunk_count: 0,
      parse_time_ms: null,
      created_at: "2026-08-08T17:50:00",
      updated_at: "2026-08-08T17:50:12",
      attempt_count: 3,
      finished_at: "2026-08-08T17:50:12",
      parse_quality_status: "FALLBACK_FAILED",
      parse_quality: {
        schema_version: 2,
        status: "FALLBACK_FAILED",
        pdf_page_count: 8,
        markdown_page_count: 8,
        text_coverage_ratio: 0.5,
        ocr_page_count: 0,
        ocr_required_pages: [3, 4, 7, 8],
        low_confidence_pages: [],
        warnings: ["PAGE_3_OCR_REQUIRED", "PAGE_4_OCR_REQUIRED"],
        fallback: {
          status: "FAILED",
          processed_page_count: 4,
          failed_page_count: 4,
          warnings: ["VISION_PROVIDER_UNAVAILABLE"],
          results: [],
        },
      },
    },
  ],
  2002: [
    {
      ...baseDocument,
      document_id: 3101,
      dataset_id: 2002,
      filename: "工业节能管理办法（预览）.html",
      file_type: "html",
      file_size: 128400,
      parser_backend: "builtin",
      status: "READY",
      error_message: null,
      page_count: null,
      chunk_count: 54,
      parse_time_ms: 2380,
      created_at: "2026-08-08T10:15:00",
      updated_at: "2026-08-08T10:15:03",
    },
  ],
  2003: [],
};

export function getMockDocuments(datasetId) {
  return mockDocumentsByDataset[datasetId] ?? [];
}

const previewChunkBase = {
  document_version: 1,
  chunk_role: "mixed",
  created_at: "2026-08-09T09:10:19",
  updated_at: "2026-08-09T09:10:19",
};

export const mockDocumentChunksByDocument = {
  3001: [
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3001-0",
      chunk_index: 0,
      chunk_type: "heading",
      content: "# 企业温室气体排放核算边界\n\n本指南用于明确企业温室气体排放核算的组织边界、报告边界和数据质量要求。",
      char_count: 58,
      start_line: 1,
      end_line: 4,
      start_page: 1,
      end_page: 1,
      structure: { heading_trail: ["企业温室气体排放核算边界"], split_strategy: "candidate_boundary + noop", chunk_role: "mixed", element_types: ["heading", "paragraph"] },
    },
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3001-1",
      chunk_index: 1,
      chunk_type: "mixed",
      content: "企业应以法人或视同法人的独立核算单位为边界，识别边界内燃料燃烧、工业生产过程、外购电力和热力等排放源。",
      char_count: 51,
      start_line: 6,
      end_line: 12,
      start_page: 3,
      end_page: 4,
      structure: { heading_trail: ["核算边界", "排放源识别"], split_strategy: "candidate_boundary + noop", chunk_role: "mixed", element_types: ["paragraph", "list"] },
    },
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3001-2",
      chunk_index: 2,
      chunk_type: "table",
      content: "| 能源品种 | 活动数据单位 | 排放因子单位 |\n| --- | --- | --- |\n| 天然气 | 万立方米 | 吨二氧化碳/万立方米 |",
      char_count: 85,
      start_line: 14,
      end_line: 17,
      start_page: 18,
      end_page: 18,
      structure: { heading_trail: ["排放量计算", "燃料燃烧"], split_strategy: "candidate_boundary + noop", chunk_role: "derived_element", element_types: ["table"], source_chunk_index: 1, protected_element_types: ["table"] },
    },
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3001-3",
      chunk_index: 3,
      chunk_type: "mixed",
      content: "天然气燃烧二氧化碳排放量可按活动数据、低位发热量、单位热值含碳量和碳氧化率计算；采用直接排放因子时，应说明因子来源和适用年份。",
      char_count: 62,
      start_line: 19,
      end_line: 27,
      start_page: 18,
      end_page: 19,
      structure: { heading_trail: ["排放量计算", "燃料燃烧"], split_strategy: "candidate_boundary + noop", chunk_role: "mixed", element_types: ["paragraph"] },
    },
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3001-4",
      chunk_index: 4,
      chunk_type: "list",
      content: "数据质量控制至少包括：\n- 核对计量器具和原始凭证；\n- 统一时间边界与计量单位；\n- 记录缺失数据的替代方法；\n- 保存排放因子版本。",
      char_count: 70,
      start_line: 29,
      end_line: 35,
      start_page: 32,
      end_page: 32,
      structure: { heading_trail: ["数据质量管理"], split_strategy: "candidate_boundary + noop", chunk_role: "mixed", element_types: ["paragraph", "list"] },
    },
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3001-5",
      chunk_index: 5,
      chunk_type: "paragraph",
      content: "核算报告应披露组织边界、排放源、活动数据、排放因子、计算方法、不确定性说明以及内部质量控制程序。",
      char_count: 48,
      start_line: 37,
      end_line: 42,
      start_page: 41,
      end_page: 42,
      structure: { heading_trail: ["报告要求"], split_strategy: "candidate_boundary + noop", chunk_role: "mixed", element_types: ["paragraph"] },
    },
  ],
  3101: [
    {
      ...previewChunkBase,
      chunk_id: "preview-chunk-3101-0",
      chunk_index: 0,
      chunk_type: "mixed",
      content: "重点用能单位应建立能源管理制度，明确能源计量、统计分析和节能目标责任。",
      char_count: 36,
      start_line: 1,
      end_line: 8,
      start_page: null,
      end_page: null,
      structure: { heading_trail: ["能源管理"], split_strategy: "candidate_boundary + noop", chunk_role: "mixed", element_types: ["heading", "paragraph"] },
    },
  ],
};

export function getMockDocumentChunks(documentId) {
  return mockDocumentChunksByDocument[documentId] ?? [];
}

const mockPreviewMarkdown3001 = [
  "# 企业温室气体排放核算边界",
  "",
  "本指南用于明确企业温室气体排放核算的组织边界、报告边界和数据质量要求。",
  "",
  "## 核算边界与排放源识别",
  "",
  "企业应以法人或视同法人的独立核算单位为边界，识别边界内燃料燃烧、工业生产过程、外购电力和热力等排放源。",
  "",
  "## 排放量计算",
  "",
  "| 能源品种 | 活动数据单位 | 排放因子单位 |",
  "| --- | --- | --- |",
  "| 天然气 | 万立方米 | 吨二氧化碳/万立方米 |",
  "",
  "天然气燃烧二氧化碳排放量可按活动数据、低位发热量、单位热值含碳量和碳氧化率计算；采用直接排放因子时，应说明因子来源和适用年份。",
  "",
  "## 数据质量管理",
  "",
  "数据质量控制至少包括：",
  "- 核对计量器具和原始凭证；",
  "- 统一时间边界与计量单位；",
  "- 记录缺失数据的替代方法；",
  "- 保存排放因子版本。",
  "",
  "## 报告要求",
  "",
  "核算报告应披露组织边界、排放源、活动数据、排放因子、计算方法、不确定性说明以及内部质量控制程序。",
].join("\n");

export const mockDocumentPreviewsByDocument = {
  3001: {
    content: mockPreviewMarkdown3001,
    map: {
      document_id: 3001,
      dataset_id: 2001,
      document_version: 1,
      boundary_precision: "line",
      map_reliable: true,
      reparse_required: false,
      source_chunk_count: 6,
      derived_chunk_count: 0,
      boundaries: [
        { boundary_index: 0, chunk_id: "preview-chunk-3001-0", chunk_index: 0, chunk_type: "mixed", start_line: 0, end_line: 3, start_page: 1, end_page: 1, heading_trail: [], split_strategy: "candidate_boundary + noop" },
        { boundary_index: 1, chunk_id: "preview-chunk-3001-1", chunk_index: 1, chunk_type: "mixed", start_line: 4, end_line: 7, start_page: 3, end_page: 4, heading_trail: ["核算边界"], split_strategy: "candidate_boundary + noop" },
        { boundary_index: 2, chunk_id: "preview-chunk-3001-2", chunk_index: 2, chunk_type: "mixed", start_line: 8, end_line: 13, start_page: 18, end_page: 18, heading_trail: ["排放源识别"], split_strategy: "candidate_boundary + noop" },
        { boundary_index: 3, chunk_id: "preview-chunk-3001-3", chunk_index: 3, chunk_type: "table", start_line: 14, end_line: 15, start_page: 18, end_page: 19, heading_trail: ["排放量计算"], split_strategy: "candidate_boundary + noop" },
        { boundary_index: 4, chunk_id: "preview-chunk-3001-4", chunk_index: 4, chunk_type: "mixed", start_line: 16, end_line: 23, start_page: 32, end_page: 32, heading_trail: ["数据质量管理"], split_strategy: "candidate_boundary + noop" },
        { boundary_index: 5, chunk_id: "preview-chunk-3001-5", chunk_index: 5, chunk_type: "mixed", start_line: 24, end_line: 26, start_page: 41, end_page: 42, heading_trail: ["报告要求"], split_strategy: "candidate_boundary + noop" },
      ],
    },
  },
  3101: {
    content: "# 能源管理\n\n重点用能单位应建立能源管理制度，明确能源计量、统计分析和节能目标责任。",
    map: {
      document_id: 3101,
      dataset_id: 2002,
      document_version: 1,
      boundary_precision: "line",
      map_reliable: true,
      reparse_required: false,
      source_chunk_count: 1,
      derived_chunk_count: 0,
      boundaries: [
        { boundary_index: 0, chunk_id: "preview-chunk-3101-0", chunk_index: 0, chunk_type: "mixed", start_line: 0, end_line: 2, start_page: null, end_page: null, heading_trail: [], split_strategy: "candidate_boundary + noop" },
      ],
    },
  },
};

export function getMockDocumentPreview(documentId) {
  return mockDocumentPreviewsByDocument[documentId] ?? null;
}

const mockDocumentAnalysisMarkdown = [
  "# 企业文档分析报告",
  "",
  "## 1. 报告摘要",
  "",
  "当前材料围绕企业温室气体核算边界、排放量计算和数据质量管理展开。[文档片段1]",
  "",
  "## 2. 评价对象和目标",
  "",
  "文档已经覆盖核算边界、排放源、计算方法和数据质量等核心主题，但具体企业信息、报告期活动数据及实际核算结果仍需结合正式企业材料补充。[文档片段1][文档片段2]",
  "",
  "## 3. 评价方法和工具",
  "",
  "当前材料已提及核算方法和数据质量要求，但具体标准版本与工具信息待补充。[文档片段1]",
  "",
  "## 4. 评价边界界定",
  "",
  "组织边界、时间边界和生命周期边界需结合企业实际资料确认。[文档片段1]",
  "",
  "## 5. 功能单位或核算口径",
  "",
  "当前材料未形成可用于结果比较的明确功能单位。",
  "",
  "## 6. 生命周期与活动数据清单分析",
  "",
  "需分别补充上游采购、内部生产、下游销售、使用和废弃处理阶段的活动数据与物料流。[文档片段2]",
  "",
  "## 7. 碳足迹核算及评价",
  "",
  "企业实际数据和核算结果尚未出现，现有材料不能支持结果复算。[文档片段2]",
  "",
  "## 8. 量化数据质量与可靠性",
  "",
  "建议补充数据来源、时间代表性、地域代表性、技术代表性和排除项说明。",
  "",
  "## 9. 不确定性分析",
  "",
  "当前片段未提供方法、参数或情景不确定性的量化结果。",
  "",
  "## 10. 文档规范性检查",
  "",
  "| 序号 | 检查项 | 结论 | 发现与证据 | 改进建议 |",
  "| --- | --- | --- | --- | --- |",
  "| 1 | 核算边界 | 满足 | 已说明组织边界与排放源识别要求。[文档片段1] | 在企业报告中进一步列出纳入和排除的组织实体。 |",
  "| 2 | 活动数据 | 部分满足 | 已说明计量数据要求，但未包含企业实际活动数据。[文档片段2] | 补充报告期能耗、计量凭证和单位换算。 |",
  "| 3 | 排放因子 | 部分满足 | 要求说明因子来源和适用年份，但当前材料未给出企业采用值。[文档片段2] | 补充因子数值、来源、版本和适用年度。 |",
  "| 4 | 不确定性分析 | 无法判断 | 当前片段未提供量化不确定性结果。 | 补充参数不确定性、方法不确定性及敏感性说明。 |",
  "",
  "## 11. 资料缺口与整改建议",
  "",
  "| 优先级 | 缺少或待确认资料 | 影响 | 建议动作 |",
  "| --- | --- | --- | --- |",
  "| 高 | 报告期活动数据与原始凭证 | 无法复算 | 补充能源、物料数据及计量凭证 |",
  "| 高 | 排放因子来源、版本和适用年份 | 无法验证参数 | 补充数值、发布机构与年度 |",
  "",
  "## 12. 结论与分析限制",
  "",
  "可将当前材料作为企业报告编制检查框架，下一步应补齐企业事实数据后重新分析。",
  "",
  "本报告是基于当前文档内容的大模型辅助分析，未接入外部基础知识库，不能替代正式第三方核查、审计、认证或法规意见。",
].join("\n");

export function getMockDocumentAnalysis(documentId) {
  const preview = getMockDocumentPreview(documentId);
  if (!preview) return null;
  const boundaries = preview.map.boundaries || [];
  const sourceIndexes = new Set([1, 2]);
  return {
    document_id: Number(documentId),
    dataset_id: Number(preview.map.dataset_id),
    document_version: Number(preview.map.document_version),
    filename: documentId === 3001 ? "企业温室气体排放核算指南.pdf" : "能源管理制度.docx",
    markdown: mockDocumentAnalysisMarkdown,
    sources: boundaries
      .map((boundary, index) => ({
        citation_index: index + 1,
        chunk_id: boundary.chunk_id,
        chunk_index: boundary.chunk_index,
        chunk_type: boundary.chunk_type,
        page: boundary.start_page === boundary.end_page ? boundary.start_page : null,
        page_range: boundary.start_page != null && boundary.end_page != null && boundary.start_page !== boundary.end_page
          ? { start: boundary.start_page, end: boundary.end_page }
          : null,
        excerpt: boundary.heading_trail?.length
          ? `文档章节：${boundary.heading_trail.join(" / ")}`
          : "企业温室气体核算报告的基础说明与适用范围。",
      }))
      .filter((source) => sourceIndexes.has(source.citation_index)),
    model_name: "预览分析模型",
    model_config_id: 1003,
    usage: { prompt_tokens: 2680, completion_tokens: 1240, total_tokens: 3920 },
    analyzed_chunk_count: boundaries.length,
    evidence_batch_count: 1,
    generated_at: new Date().toISOString(),
  };
}

export const mockRecallResponse = {
  preview: true,
  request_id: "preview-recall-request",
  query: "企业天然气燃烧排放如何核算？",
  hits: [
    {
      chunk_id: "preview-chunk-001",
      doc_id: 3001,
      dataset_id: 2001,
      filename: "温室气体排放核算指南（预览）.pdf",
      page: 18,
      page_range: "18-19",
      document_version: 1,
      chunk_index: 76,
      citation_index: 1,
      fused_score: 0.9134,
      scores: { bm25: 8.42, sparse: 0.74, dense: 0.86 },
      content: "天然气燃烧排放可按活动数据与相应排放因子的乘积计算。",
    },
    {
      chunk_id: "preview-chunk-002",
      doc_id: 3001,
      dataset_id: 2001,
      filename: "温室气体排放核算指南（预览）.pdf",
      page: 21,
      page_range: "21",
      document_version: 1,
      chunk_index: 88,
      citation_index: 2,
      fused_score: 0.8241,
      scores: { bm25: 6.18, sparse: 0.68, dense: 0.79 },
      content: "活动数据应优先采用经校验计量器具得到的实际消耗量。",
    },
  ],
  per_source_counts: { bm25: 20, sparse: 20, dense: 20 },
  failed_sources: [],
  elapsed_ms: 286,
  recall_diagnostics: {
    source_mode: "hybrid",
    degraded: false,
    active_sources: ["bm25", "sparse", "dense"],
    per_source_counts: { bm25: 20, sparse: 20, dense: 20 },
    empty_sources: [],
    failed_sources: [],
  },
};

export const mockStreamEvents = [
  {
    event: "stream_started",
    data: { request_id: "preview-stream-request" },
  },
  {
    event: "answer_delta",
    data: { text: "可以按照“活动数据 × 排放因子”计算。" },
  },
  {
    event: "answer_done",
    data: {
      request_id: "preview-stream-request",
      answer: "可以按照“活动数据 × 排放因子”计算。[片段1]",
      usage: { prompt_tokens: 428, completion_tokens: 38, total_tokens: 466 },
      hits: mockRecallResponse.hits,
      failed_sources: [],
      elapsed_ms: 286,
    },
  },
];

export const mockEmptyRecallEvents = [
  {
    event: "stream_started",
    data: { request_id: "preview-empty-request" },
  },
  {
    event: "recall_done",
    data: {
      request_id: "preview-empty-request",
      hits: [],
      failed_sources: [],
    },
  },
];
